### ISSUE TITLE
[Bug] AG-UI event adapter does not emit `TEXT_MESSAGE_END` event prior to `TOOL_CALL_START`

### ISSUE THREAD

**Issue by sirianni** [agno-agi/agno#4378]
### Description

Originally reported here https://github.com/agno-agi/agno/issues/3554#issuecomment-3217243963

AG-UI client side is failing validation for message events sent using Agno's AG-UI adapter.

The verification code [here](https://github.com/ag-ui-protocol/ag-ui/blob/1a7fcc2d8191939b9fc139d0cf8633865e7bf6f3/typescript-sdk/packages/client/src/verify/verify.ts#L63) requires that a `TEXT_MESSAGE_END` be received prior to a `TOOL_CALL_START`, however the Agno implementation is not doing that properly

```
data: {"type":"TEXT_MESSAGE_CONTENT","messageId":"698abc6c-e6c6-4aa2-8a5b-6a45bc62c986","delta":"."}

data: {"type":"TOOL_CALL_START","toolCallId":"toolu_bdrk_01BXYNZ11WVZLwvtg2sR2axJ","toolCallName":"foobar","parentMessageId":"698abc6c-e6c6-4aa2-8a5b-6a45bc62c986"}
```

The linked issue proposes a fix
```python
    # Handle starting a new tool call
    elif chunk.event == RunEvent.tool_call_started:

        # [ ... Start of fix .... ]
        # End the current text message if one is active before starting tool calls
        if message_started:
            end_message_event = TextMessageEndEvent(type=EventType.TEXT_MESSAGE_END, message_id=message_id)
            events_to_emit.append(end_message_event)
            message_started = False  # Reset message_started state
        # [ ... End of fix .... ]
```

### Steps to Reproduce

See above

### Expected Behavior

See above

### Actual Behavior

See above

### Environment

```markdown
n/a
```

**Comment by dirkbrnd** [comment]
We'll take a look!

**Comment by georgeneokq** [comment]
Hi @dirkbrnd , I actually made an issue #4157  around 3 weeks ago, also related to incorrect order of event emission in AGUIApp. I also linked a pull request in that issue, but the issue was closed even though it wasn't fixed yet, and my pull request #4158  has been left hanging even after a few releases. Could you please take a look at that too?

**Comment by jamie0725** [comment]
Hi @dirkbrnd, this issue has not been solved yet, could you have a look?

Also, starting from Agno 2.0, I notice a new bug related to AG-UI events: each tool call now emits two ToolCallResultEvent with same results but different `msg_id`.

The problem lies in https://github.com/agno-agi/agno/blob/main/libs/agno/agno/os/interfaces/agui/utils.py#L171C2-L172C51, which should be:

```
    elif chunk.event == RunEvent.tool_call_started:
        # End the current text message if one is active before starting tool calls
        if current_message_id is not None:
            end_message_event = TextMessageEndEvent(
                type=EventType.TEXT_MESSAGE_END, message_id=current_message_id
            )
            events_to_emit.append(end_message_event)
            current_message_id = None
```

**Comment by tom1978** [comment]
This issue has existed since version 1.x, and it’s unclear why it has never been fixed.

**Comment by Mustafa-Esoofally** [comment]
Hey @sirianni and @tom1978 ! We released a fix for this in our new [2.0.5](https://pypi.org/project/agno/) release.

**Comment by dirkbrnd** [comment]
Sorry.@sirianni @tom1978 @jamie0725 for any confusion or that it looks like we dismissed it. 
The AG UI protocol changed while we were making updates, and a few changes were missed.

Please let us know what issues remain after 2.0.5
